### ISSUE TITLE
Graphical menu configuration does not show all options

### ISSUE THREAD

**Issue by jonathanpoelen** [xmake-io/xmake#1035] opened 2020-11-14 03:22 UTC
When there are many options and/or the window is too small, not all options can be displayed. Unfortunately, there is no scroll.

### Menu Config

![a](https://user-images.githubusercontent.com/1436727/99138361-6b92ca80-2630-11eb-8786-c578af52a50f.png)

31 options, but no scroll. After `control_flow`, the focus goes back to `msvc_isystem`.  
Window resizing is also ignored.

### Value selector

![b](https://user-images.githubusercontent.com/1436727/99138365-6fbee800-2630-11eb-84e4-5bcf7b0e3ca4.png)

20 values, the focus can cycle through them all, but the rendering does not change. Here, the focus is on an displayed value.

### Help and Search menu

![c](https://user-images.githubusercontent.com/1436727/99138369-74839c00-2630-11eb-8390-15fc677deaac.png)

Ok, scroll present and functional.

**Comment by waruqi** [comment] 2020-11-14 08:45
This requires adding a scroll bar in the menuconf view, and I will consider supporting it in future versions.

**Comment by waruqi** [comment] 2020-11-16 02:29
xmake 2.3.9 will be released soon, I will improve the support rolling issue in the next version.

**Comment by waruqi** [comment] 2020-11-20 14:54
Although I have not yet supported scrolling for the menuconf/choicebox view, I have added support for mouse events. on dev branch.

**Comment by waruqi** [comment] 2020-11-29 14:59
I have added scrollbar to support it on dev branch. `xmake update -s dev`

**Comment by waruqi** [comment] 2020-11-29 15:00
![Snip20201129_20](https://user-images.githubusercontent.com/151335/100545383-87d07180-3296-11eb-9a27-9aea569b543a.png)

**Comment by jonathanpoelen** [comment] 2020-11-30 02:33
Few bugs:

- `<Back>` button does not work after a scrolling to the next page (basic config -> scroll to the second page -> back -> ???). Then there is an error with `<Select>` button.
```
error: @programdir/core/ui/menuconf.lua:247: attempt to index local 'item' (a nil value)
```
- Key up is not circular, it is positioned at the last item of the first page rather than the last item of the last page.
- Option list is empty when it is reopened after a scroll (basic config -> platform -> scroll to second page -> cancel -> reopen)
- Scrolling is invisible in the help widget.

It would be nice if page up/down scrolls to the next/previous page.

**Comment by waruqi** [comment] 2020-11-30 02:53
> <Back> button does not work after a scrolling to the next page (basic config -> scroll to the second page -> back -> ???). Then there is an error with <Select> button.

I will fix it later.

> Key up is not circular, it is positioned at the last item of the first page rather than the last item of the last page.

This will be more complicated to implement, I don’t have time to improve it now, just the current list loop is acceptable.

> Option list is empty when it is reopened after a scroll (basic config -> platform -> scroll to second page -> cancel -> reopen)

I will look at it.

> It would be nice if page up/down scrolls to the next/previous page.

I don’t have these two key buttons on my keyboard, so I can’t test it. 

> Scrolling is invisible in the help widget.

It works for me, the scroll bar is only displayed when the text is not fully displayed

![Snip20201130_21](https://user-images.githubusercontent.com/151335/100563161-b7b06100-32f8-11eb-90a5-0d01eea5ca7f.png)

**Comment by waruqi** [comment] 2020-11-30 13:05
> Back button does not work after a scrolling to the next page (basic config -> scroll to the second page -> back -> ???). Then there is an error with Select button.

I have fixed it on dev branch.

**Comment by waruqi** [comment] 2020-11-30 13:14
> Option list is empty when it is reopened after a scroll (basic config -> platform -> scroll to second page -> cancel -> reopen)

I have also fixed it.

**Comment by waruqi** [comment] 2020-11-30 13:25
> It would be nice if page up/down scrolls to the next/previous page.

I have added it, but I cannot test it.

**Comment by jonathanpoelen** [comment] 2020-11-30 15:54
> I don’t have these two key buttons on my keyboard, so I can’t test it.

If you have Linux, there are tools like xdotools that can simulate key (`xdotool key Page_Up`).

> > Scrolling is invisible in the help widget.
> It works for me, the scroll bar is only displayed when the text is not fully displayed

Ah, it seems that it was only after a resize (`xmake f --menu` -> resize -> basic conf -> platform -> help -> possibly no scrollbar in help)

> > Back button does not work after a scrolling to the next page (basic config -> scroll to the second page -> back -> ???). Then there is an error with Select button.
> 
> I have fixed it on dev branch.
> 
> > Option list is empty when it is reopened after a scroll (basic config -> platform -> scroll to second page -> cancel -> reopen)
> 
> I have also fixed it.

I confirm.

> > It would be nice if page up/down scrolls to the next/previous page.
>
> I have added it, but I cannot test it.

`e.key_name == "PageDown" or e.key_name == "PageUp"` is missing in `mconfdialog:on_event` and `mconfdialog:on_event`, but the behavior is unnatural. I will do a PR when I have time.

**Comment by waruqi** [comment] 2020-12-01 01:39
> Ah, it seems that it was only after a resize (xmake f --menu -> resize -> basic conf -> platform -> help -> possibly no scrollbar in help)

Oh, I works for me, I still can't reproduce it.

**Comment by waruqi** [comment] 2020-12-04 14:26
I cannot reproduce other issues at the moment, so I can only close this issue first.

**Closed by waruqi** 2020-12-04 14:26 UTC
Labels: improvement
