### ISSUE TITLE
Allow setting package urls to empty

### ISSUE THREAD

**Issue by Qudix** [xmake-io/xmake#4213] opened 2023-09-18 17:10 UTC
### Is your feature request related to a problem? Please describe.

At the moment if you have this scenario:

In xrepo:
```lua
package("foo")
    set_urls(...)
    ...
```

And in your local script you define another package that uses it as a base with `sourcedir` set to a submodule of foo:
```lua
package("bar")
    set_base("foo")
    set_sourcedir(path.join(os.scriptdir(), "extern/foo"))
```

...xmake will still download and install foo using the `urls` set in foo.

### Describe the solution you'd like

Allow something like
```lua
package("bar")
    set_base("foo")
    set_urls(nil)
    set_sourcedir(path.join(os.scriptdir(), "extern/foo"))
```
...or some other simple syntax to clear all of a packages URLs so that `package:is_source_embed` equals true and it installs locally instead.

https://github.com/xmake-io/xmake/blob/00fe8d37c2f6ebe818d2d755d97c2a5a0bd1d6a8/xmake/core/package/package.lua#L617-L619

### Describe alternatives you've considered

This can currently be done using `on_load`
```lua
on_load(function(package)
    package:urls_set({})
end)
```
...but it's quite unwieldy and a simpler solution would be nicer.

**Comment by waruqi** [comment] 2023-09-19 01:24
try it again. `xmake update -s dev`

**Comment by Qudix** [comment] 2023-09-19 01:56
Doesn't seem to work, it still downloads it remotely.

**Comment by Qudix** [comment] 2023-09-19 02:04
Test case: 
[test.zip](https://github.com/xmake-io/xmake/files/12654918/test.zip)

**Comment by waruqi** [comment] 2023-09-19 02:29
try it again.

```
xmake update -s dev
```

```
set_urls("")
```

**Comment by Qudix** [comment] 2023-09-19 03:41
That does seem to sort of work, but looking at this from a distant perspective it seems this may not be the correct route for what it is I'm trying to achieve overall.

The only reason I'm using local packages alongside their xrepo rules is because I'm trying to allow a library to be submoduled to a project, so that the user can use the rules, and build and modify the library locally to test changes while linking with it at the same time.

A better solution, for xmake using libraries, would be to have the rules included with the library itself. Then you can just include the submoduled library and add it as a dependency. The problem with this right now is that the xrepo package also needs access to those rules for `add_requires` use, so you'd have to host a copy on xrepo also.

**Comment by waruqi** [comment] 2023-09-19 04:43
I don't understand what you mean, if the issue is working now, you can close it first. And open a new issue to describe your problem in more detail.

**Closed** 2023-09-19 04:47 UTC
Labels: feature request
