### ISSUE TITLE
Visual Studio generator uses release libraries in debug

### ISSUE THREAD

**Issue by SirLynix** [xmake-io/xmake#1071] opened 2020-11-25 07:43 UTC
# Describe the bug
When generating a Visual Studio (vs) project, it uses releases libraries in debug (and 64bits libraries in 32bits).

### Expected behavior
That it uses the right library in the right configuration.

### Error output
When compiling in debug:
```
Build started...
1>------ Build started: Project: test_curl, Configuration: debug x64 ------
1>fmt.lib(format.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.obj
1>fmt.lib(format.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MDd_DynamicDebug' in main.obj
1>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
1>..\..\build\windows\x64\debug\test_curl.exe : fatal error LNK1319: 2 mismatches detected
1>Done building project "test_curl.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

I did check the libdir, it's the same for debug and release.

release/debug x86 are not working at all.
![image](https://user-images.githubusercontent.com/3002461/100197068-18572c80-2efa-11eb-8e11-707b5988eca7.png)

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake v2.3.9+202011250023
- os: Windows 10 2004
- target platform: Windows

### Additional context
xmake.lua:
```lua
-- pass debug option, and it should be `configs` not `config`
add_requires("fmt", { debug = is_mode("debug"), configs = { header_only = false, vs_runtime = "MD"} })

add_rules("mode.debug", "mode.release")
add_cxflags(is_mode("debug") and "/MDd" or "/MD")

target("test_curl")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("fmt")
```

src/main.cpp:

```cpp
#include <fmt/core.h>

int main() {
  fmt::print("Hello, world!\n");
}
```

**Comment by waruqi** [comment] 2020-11-25 08:00
This may be caused by the configuration cache, but to completely solve this problem, I need to repair my vs environment before further debugging.

I will fix it in this version, but please wait some time.

**Comment by waruqi** [comment] 2020-12-17 16:16
This is because the cache is not reset after switching between different architectures and modes. I will improve it. 

In addition, after solving the cache problem, all dependent packages will be installed when the project is generated. 

And https://github.com/xmake-io/xmake/issues/1078 This issue will also be better resolved at the same time.

**Comment by waruqi** [comment] 2020-12-23 10:51
I rewrite the whole cache module and have solved this problem. you can update to `cache` branch and try it again. `xmake update -s github:xmake-io/xmake#cache`

xmake will install all required packages when generating vs/vsxmake projects now.

**Comment by SirLynix** [comment] 2020-12-23 15:56
Seems good except for a little bug:
```
lynix@SirLynixVanDesktop:/mnt/c/Projets/Burgwar/BurgWar$ xmake.exe project -k vsxmake
checking for debug.x86 ...
checking for Microsoft Visual Studio (x86) version ... 2019
note: try installing these packages (pass -y to skip confirm)?
in burgwar-repo:
  -> libcurl 7.73.0 (debug)
  -> nazaraengine 20201119 (debug)
  -> nazaraengine~server 20201119 (debug)
please input: y (y/n)
y
  => installing libcurl, nazaraengine, nazaraengine~server .. (3/cmake,msbuild.ex..) ⠸
  => install nazaraengine~server 20201119 .. ok
  => installing libcurl, nazaraengine .. (2/cmake,msbuild.ex..) ⠹
  => install nazaraengine 20201119 .. ok
  => install libcurl 7.73.0 .. ok
checking for Qt SDK directory ... C:/Projets/Libs/Qt/5.15.0/msvc2019_64
checking for Qt SDK version ... 5.15.0
checking for debug.x64 ...
checking for Microsoft Visual Studio (x64) version ... 2019
checking for Qt SDK directory ... C:/Projets/Libs/Qt/5.15.0/msvc2019_64
checking for Qt SDK version ... 5.15.0
checking for release.x86 ...
note: try installing these packages (pass -y to skip confirm)?
in burgwar-repo:
  -> libcurl 7.73.0
  -> nazaraengine 20201119
  -> nazaraengine~server 20201119
please input: y (y/n)
y
  => installing libcurl, nazaraengine, nazaraengine~server .. (3/cmake,msbuild.ex..) ⠇
  => install nazaraengine~server 20201119 .. ok
  => installing libcurl, nazaraengine .. (2/cmake,msbuild.ex..) ⠋
  => install nazaraengine 20201119 .. ok
  => install libcurl 7.73.0 .. ok
checking for Qt SDK directory ... C:/Projets/Libs/Qt/5.15.0/msvc2019_64
checking for Qt SDK version ... 5.15.0
checking for release.x64 ...
note: try installing these packages (pass -y to skip confirm)?
in burgwar-repo:
  -> libcurl 7.73.0
please input: y (y/n)
y
  => install libcurl 7.73.0 .. failed
if you want to get verbose errors, please see:
  -> C:\Users\Lynix\AppData\Local\.xmake\cache\packages\2012\l\libcurl\7.73.0\installdir.failed\logs\install.txt
error: install failed!
```

log contains:
```
attempt to index local 'msbuild' (a nil value)
```

But running it a second time works
```
$ xmake.exe project -k vsxmake
checking for Qt SDK directory ... C:/Projets/Libs/Qt/5.15.0/msvc2019_64
checking for Qt SDK version ... 5.15.0
checking for debug.x86 ...
checking for Microsoft Visual Studio (x86) version ... 2019
checking for Qt SDK directory ... C:/Projets/Libs/Qt/5.15.0/msvc2019_64
checking for Qt SDK version ... 5.15.0
checking for debug.x64 ...
checking for Microsoft Visual Studio (x64) version ... 2019
checking for Qt SDK directory ... C:/Projets/Libs/Qt/5.15.0/msvc2019_64
checking for Qt SDK version ... 5.15.0
checking for release.x86 ...
checking for Qt SDK directory ... C:/Projets/Libs/Qt/5.15.0/msvc2019_64
checking for Qt SDK version ... 5.15.0
checking for release.x64 ...
note: try installing these packages (pass -y to skip confirm)?
in burgwar-repo:
  -> libcurl 7.73.0
please input: y (y/n)
y
  => install libcurl 7.73.0 .. ok
checking for Qt SDK directory ... C:/Projets/Libs/Qt/5.15.0/msvc2019_64
checking for Qt SDK version ... 5.15.0
create ok!
```

**Comment by waruqi** [comment] 2020-12-24 02:00
Ok, I will look at it, btw I will improve vs_runtime later. see https://github.com/xmake-io/xmake/issues/1155

**Comment by waruqi** [comment] 2020-12-24 09:14
I have improved vs project plugin and vs_runtime, you can install `cache` branch version from ci. https://github.com/xmake-io/xmake/suites/1720734652/artifacts/32543053

And we need only write the following configuration.

```lua
add_requires("fmt", {configs = { header_only = false} })

add_rules("mode.debug", "mode.release")

target("test_curl")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("fmt")
```

In addition, I added `xmake f --vs_runtime=MT/MD/MTd/MDd` option to switch vs runtime fastly, and `add_requires()` will also switch vs runtime at same time.

And we can also use `set_runtimes("MT")` to set vs runtime for the given target. It is equivalent to `/MT` + `-nodefaultlib:msvcrt.lib`

only for target:

`set_runtimes("MT")` -> `/MT` + `-nodefaultlib:msvcrt.lib`
`set_runtimes("MTd")` -> `/MTd` + `-nodefaultlib:msvcrt.lib`
`set_runtimes("MD")` -> `/MD`
`set_runtimes("MDd")` -> `/MDd`

only for package

`add_requires("xxx", {configs = {vs_runtime = "MT/MTd/MD/MDd"}})

for target and packages (global)

`xmake f --vs_runtime="MD"`

by default: 

`MT`

**Comment by waruqi** [comment] 2020-12-24 09:17
> attempt to index local 'msbuild' (a nil value)

I can’t reproduce it, maybe it’s caused by the configuration cache, because I refactored the entire cache, maybe we need to clear the old cache first

**Comment by SirLynix** [comment] 2020-12-24 09:27
I couldn't reproduce it either. Maybe it's an old cache issue. If I happen to reproduce it I'll make an issue.

The changes for vs_runtime seem amazing! Thank you 😄

**Comment by waruqi** [comment] 2020-12-24 09:32
> I couldn't reproduce it either. Maybe it's an old cache issue. If I happen to reproduce it I'll make an issue.
> 
> The changes for vs_runtime seem amazing! Thank you 😄

You can use `cache` version to  try this configuration, I am going to merge it if it works.

```
add_requires("fmt", {configs = { header_only = false} })

add_rules("mode.debug", "mode.release")

target("test_curl")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("fmt")
```

**Comment by waruqi** [comment] 2020-12-24 09:46
Maybe you need this.

```lua
local vs_runtime = is_mode("debug") and "MDd" or "MD"

add_requires("fmt", {configs = { header_only = false, vs_runtime = vs_runtime} })
add_rules("mode.debug", "mode.release")
set_runtimes(vs_runtime)

target("test_curl")
    set_kind("binary")
    add_files("src/*.cpp")
    add_packages("fmt")
```

**Comment by waruqi** [comment] 2020-12-24 10:42
Now we can use this on cache branch.

```lua
set_runtimes("MD") -- for all targets and packages by default
add_requires("aa", "bb", "cc") -- MD
add_requires("yy", {configs = {vs_runtime = "MT"}}) -- for special package
target("xxx")
    set_runtimes("MT") -- for special target
```

**Closed** 2020-12-24 14:21 UTC
Labels: generator, improvement
