### ISSUE TITLE
vsxmake stops intellisense

### ISSUE THREAD

**Issue by yamashi** [xmake-io/xmake#1156] opened 2020-12-23 16:30 UTC
### Describe the bug
Using xmake project -k vsxmake on https://github.com/yamashi/CyberEngineTweaks generates a project that does not work with intellisense. The project builds fine so it's intellisense that fails to retrieve symbols.

### Expected behavior
Editor doesn't show that symbols are unknown like when creating a vs project.

### Error output
https://i.imgur.com/ezHLkzK.png

### Related Environment

Please provide compiling and running environment information:

- xmake version: xmake 2.3.9/cache
- os: Windows 10 - Visual Studio 2019 latest
- target platform: Any

**Comment by SirLynix** [comment] 2020-12-23 16:37
Duplicate of #1080

**Closed** 2020-12-23 17:01 UTC
