### ISSUE TITLE
C++ newly added module import not being found

### ISSUE THREAD

**Issue by ilobilo** [xmake-io/xmake#5663] opened 2024-09-25 10:25 UTC
### Xmake Version

2.9.5

### Operating System Version and Architecture

Fedora KDE 40

### Describe Bug

I have an issue when newly imported C++ modules are not being found (so adding ``import existing_module;`` to a source file). but if I do a clean rebuild with ``xmake clean --all`` and ``xmake build``, no errors are thrown

### Expected Behavior

finds the available modules

### Project Configuration

compiles modules normally, nothing special

### Additional Information and Error Logs

nope

**Comment by waruqi** [comment] 2024-09-26 14:14
Can you provide an example? and logs?

**Comment by ilobilo** [comment] 2024-09-26 17:18
let's say that the following compiles fine:
main.cpp
```c++
import one;
import two;

int main()
{
    onefunc();
    twofunc();
    return 0;
}
```
one.cppm
```c++
export module one;
export void onefunc() { }
```
two.cppm
```c++
export module two;
export void twofunc() { }
```
now, if I modify two.cppm to this:
```c++
export module two;
import one;
export void twofunc() { onefunc(); }
```
I get an error about module `one` not being found. If I run ``xmake clean --all`` and ``xmake build``, then it compiles. I believe Arthapz in the discord server said that this was a known issue.

**Comment by waruqi** [comment] 2024-09-29 01:32
it works for me.

```console
ruki-2:test ruki$ xmake f --toolchain=llvm -c
checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for SDK version of Xcode for macosx (x86_64) ... 14.0
ruki-2:test ruki$ xmake -rv
checking for flags (clang_print_library_module_manifest_path) ... no
[  0%]: <hello> generating.module.deps src/main.cpp
[  0%]: <hello> generating.module.deps src/one.cppm
[  0%]: <hello> generating.module.deps src/two.cppm
[  0%]: <hello> generating.module.deps /usr/local/Cellar/llvm/18.1.5/bin/../lib/c++/../../share/l
ibc++/v1/std.cppm
[  0%]: <hello> generating.module.deps /usr/local/Cellar/llvm/18.1.5/bin/../lib/c++/../../share/l
ibc++/v1/std.compat.cppm
checking for /usr/local/Cellar/llvm/18.1.5/bin/clang-scan-deps ... ok
checking for flags (-fvisibility-inlines-hidden) ... ok
checking for flags (-O3) ... ok
checking for flags (-std=c++20) ... ok
checking for flags (-DNDEBUG) ... ok
/usr/local/Cellar/llvm/18.1.5/bin/clang-scan-deps --format=p1689 -- /usr/local/Cellar/llvm/18.1.5
/bin/clang -x c++ -c src/main.cpp -o build/.objs/hello/macosx/x86_64/release/src/main.cpp.o -Qunu
sed-arguments -m64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -DN
DEBUG
/usr/local/Cellar/llvm/18.1.5/bin/clang-scan-deps --format=p1689 -- /usr/local/Cellar/llvm/18.1.5
/bin/clang -x c++ -c src/two.cppm -o build/.objs/hello/macosx/x86_64/release/src/two.cppm.o -Qunu
sed-arguments -m64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -DN
DEBUG
/usr/local/Cellar/llvm/18.1.5/bin/clang-scan-deps --format=p1689 -- /usr/local/Cellar/llvm/18.1.5
/bin/clang -x c++ -c /usr/local/Cellar/llvm/18.1.5/bin/../lib/c++/../../share/libc++/v1/std.cppm
-o build/.objs/hello/macosx/x86_64/release/usr/local/Cellar/llvm/18.1.5/bin/__/lib/c++/__/__/shar
e/libc++/v1/std.cppm.o -Qunused-arguments -m64 -isysroot /Applications/Xcode.app/Contents/Develop
er/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidden -fvisibility-inlin
es-hidden -O3 -std=c++20 -DNDEBUG
/usr/local/Cellar/llvm/18.1.5/bin/clang-scan-deps --format=p1689 -- /usr/local/Cellar/llvm/18.1.5
/bin/clang -x c++ -c /usr/local/Cellar/llvm/18.1.5/bin/../lib/c++/../../share/libc++/v1/std.compa
t.cppm -o build/.objs/hello/macosx/x86_64/release/usr/local/Cellar/llvm/18.1.5/bin/__/lib/c++/__/
__/share/libc++/v1/std.compat.cppm.o -Qunused-arguments -m64 -isysroot /Applications/Xcode.app/Co
ntents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidden -fvi
sibility-inlines-hidden -O3 -std=c++20 -DNDEBUG
/usr/local/Cellar/llvm/18.1.5/bin/clang-scan-deps --format=p1689 -- /usr/local/Cellar/llvm/18.1.5
/bin/clang -x c++ -c src/one.cppm -o build/.objs/hello/macosx/x86_64/release/src/one.cppm.o -Qunu
sed-arguments -m64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform
/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++20 -DN
DEBUG
[ 37%]: <hello> compiling.module.release two
[ 50%]: <hello> compiling.module.release one
checking for flags (clang_module_output) ... ok
/usr/local/Cellar/llvm/18.1.5/bin/clang -c -Qunused-arguments -m64 -isysroot /Applications/Xcode.
app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidde
n -fvisibility-inlines-hidden -O3 -std=c++20 -DNDEBUG -x c++-module -fmodule-output=build/.gens/h
ello/macosx/x86_64/release/rules/bmi/cache/modules/c83caa2b/two.pcm -o build/.objs/hello/macosx/x
86_64/release/src/two.cppm.o src/two.cppm
checking for flags (-fdiagnostics-color=always) ... ok
/usr/local/Cellar/llvm/18.1.5/bin/clang -c -Qunused-arguments -m64 -isysroot /Applications/Xcode.
app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidde
n -fvisibility-inlines-hidden -O3 -std=c++20 -DNDEBUG -x c++-module -fmodule-output=build/.gens/h
ello/macosx/x86_64/release/rules/bmi/cache/modules/c83caa2b/one.pcm -o build/.objs/hello/macosx/x
86_64/release/src/one.cppm.o src/one.cppm
checking for flags (clang_module_file) ... ok
[ 75%]: compiling.release src/main.cpp
/usr/local/Cellar/llvm/18.1.5/bin/clang -c -Qunused-arguments -m64 -isysroot /Applications/Xcode.
app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -fvisibility=hidde
n -fvisibility-inlines-hidden -O3 -std=c++20 -DNDEBUG -fmodule-file=one=build/.gens/hello/macosx/
x86_64/release/rules/bmi/cache/modules/c83caa2b/one.pcm -fmodule-file=two=build/.gens/hello/macos
x/x86_64/release/rules/bmi/cache/modules/c83caa2b/two.pcm -o build/.objs/hello/macosx/x86_64/rele
ase/src/main.cpp.o src/main.cpp
checking for flags (-MMD -MF) ... ok
checking for clang++ ... /usr/local/Cellar/llvm/18.1.5/bin/clang++
checking for the linker (ld) ... clang++
checking for /usr/local/Cellar/llvm/18.1.5/bin/clang++ ... ok
checking for flags (-fPIC) ... ok
[ 87%]: linking.release hello
/usr/local/Cellar/llvm/18.1.5/bin/clang++ -o build/macosx/x86_64/release/hello build/.objs/hello/
macosx/x86_64/release/src/main.cpp.o build/.objs/hello/macosx/x86_64/release/src/one.cppm.o build
/.objs/hello/macosx/x86_64/release/src/two.cppm.o -m64 -isysroot /Applications/Xcode.app/Contents
/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -Wl,-x -Wl,-dead_strip
[100%]: build ok, spent 3.792s
ruki-2:test ruki$ vim ./src/two.cppm

ruki-2:test ruki$ cat ./src/two.cppm
export module two;
import one;
export void twofunc() { onefunc(); }

ruki-2:test ruki$ xmake
[  0%]: <hello> generating.module.deps src/two.cppm
[ 50%]: <hello> compiling.module.release two
[ 75%]: compiling.release src/main.cpp
[ 87%]: linking.release hello
[100%]: build ok, spent 0.86s
ruki-2:test ruki$ xmake clean --all
ruki-2:test ruki$ xmake
checking for platform ... macosx
checking for architecture ... x86_64
checking for Xcode directory ... /Applications/Xcode.app
checking for Codesign Identity of Xcode ... Apple Development: waruqi@gmail.com (T3NA4MRVPU)
checking for SDK version of Xcode for macosx (x86_64) ... 14.0
checking for Minimal target version of Xcode for macosx (x86_64) ... 14.0
[  0%]: <hello> generating.module.deps src/main.cpp
[  0%]: <hello> generating.module.deps src/one.cppm
[  0%]: <hello> generating.module.deps src/two.cppm
[ 37%]: <hello> compiling.module.release one
[ 50%]: <hello> compiling.module.release two
[ 75%]: compiling.release src/main.cpp
[ 87%]: linking.release hello
[100%]: build ok, spent 2.228s
warning: std and std.compat modules not found ! disabling them for the build, maybe try to add --
sdk=<PATH/TO/LLVM>
warning: add -v for getting more warnings ..
```

**Comment by ilobilo** [comment] 2024-09-29 09:25
I don't know why that is, I'm having this issue constantly, on almost every added import. And not on a single project, but on others as well. On at least 2 distros (Ubuntu and Fedora) and both clang 18 and 19

**Comment by ilobilo** [comment] 2024-09-29 12:11
newly added ``import system.memory.virt;`` line here
![image](https://github.com/user-attachments/assets/bc3844a9-9697-4e27-9d12-c3894100604a)
modules and source files are compiled in different targets

**Comment by waruqi** [comment] 2024-09-30 14:33
Did you provide a whole example project? you can upload it as zip assignment here.

And provide a reproducible process.

**Comment by ilobilo** [comment] 2024-10-01 07:35
@waruqi 
[example.zip](https://github.com/user-attachments/files/17201181/example.zip)

**Comment by waruqi** [comment] 2024-10-02 15:20
i meet some other errors on macOS.

```console
xmake f --toolchain=llvm
xmake
[  0%]: <ilobilix.elf> generating.module.deps kernel/interfaces/lib/net/address.cppm
[  0%]: <ilobilix.elf> generating.module.deps kernel/interfaces/lib/net/net.cppm
[  0%]: <ilobilix.elf> generating.module.deps kernel/interfaces/lib/net/ethernet.cppm
[  0%]: <ilobilix.elf> generating.module.deps kernel/interfaces/lib/bitmap.cppm
[  0%]: <ilobilix.elf> generating.module.deps kernel/interfaces/lib/path.cppm
[  0%]: <ilobilix.elf> generating.module.deps kernel/interfaces/lib/containers.cppm
[  0%]: <ilobilix.elf> generating.module.deps kernel/interfaces/lib/std.cppm
error: warning: unknown warning option '-Wno-nan-infinity-disabled' [-Wunknown-warning-option]
In file included from kernel/interfaces/lib/std.cppm:4:
In file included from /Users/ruki/Downloads/ilobilix-2/build/.packages/f/freestnd-cxx-hdrs/latest/
cd7c09d19d204c99890d581bcbc2d6ce/include/array:35:
/Users/ruki/Downloads/ilobilix-2/build/.packages/f/freestnd-cxx-hdrs/latest/cd7c09d19d204c99890d58
1bcbc2d6ce/include/bits/c++0x_warning.h:32:2: error: This file requires compiler and library suppo
rt for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11
 compiler options.
#error This file requires compiler and library support \
 ^
In file included from kernel/interfaces/lib/std.cppm:14:
/Users/ruki/Downloads/ilobilix-2/build/.packages/f/freestnd-cxx-hdrs/latest/cd7c09d19d204c99890d58
1bcbc2d6ce/include/coroutine:38:3: error: "the <coroutine> header requires -fcoroutines"
# error "the <coroutine> header requires -fcoroutines"
  ^
In file included from kernel/interfaces/lib/std.cppm:47:
In file included from /Users/ruki/Downloads/ilobilix-2/kernel/include/std/unordered_map:5:
In file included from /Users/ruki/Downloads/ilobilix-2/build/.packages/p/parallel_hashmap/latest/0
0322eb870de45fd90e87c392eacbca9/include/parallel_hashmap/phmap.h:120:
In file included from /Users/ruki/Downloads/ilobilix-2/build/.packages/p/parallel_hashmap/latest/0
0322eb870de45fd90e87c392eacbca9/include/parallel_hashmap/phmap_utils.h:34:
In file included from /Users/ruki/Downloads/ilobilix-2/build/.packages/p/parallel_hashmap/latest/0
0322eb870de45fd90e87c392eacbca9/include/parallel_hashmap/phmap_bits.h:51:
/Users/ruki/Downloads/ilobilix-2/build/.packages/p/parallel_hashmap/latest/00322eb870de45fd90e87c3
92eacbca9/include/parallel_hashmap/phmap_config.h:87:10: error: "C++ versions less than C++11 are
not supported."
        #error "C++ versions less than C++11 are not supported."
         ^
kernel/interfaces/lib/std.cppm:364:24: warning: '<=>' is a single token in C++20; add a space to a
void a change in behavior [-Wc++20-compat]
    using std::operator<=> _USING_IF_EXISTS;
                       ^

kernel/interfaces/lib/std.cppm:1031:24: warning: '<=>' is a single token in C++20; add a space to
avoid a change in behavior [-Wc++20-compat]
    using std::operator<=> _USING_IF_EXISTS;
                       ^

kernel/interfaces/lib/std.cppm:1362:24: warning: '<=>' is a single token in C++20; add a space to
avoid a change in behavior [-Wc++20-compat]
    using std::operator<=> _USING_IF_EXISTS;
                       ^

kernel/interfaces/lib/std.cppm:1512:24: warning: '<=>' is a single token in C++20; add a space to
avoid a change in behavior [-Wc++20-compat]
    using std::operator<=> _USING_IF_EXISTS;
                       ^
```

**Comment by ilobilo** [comment] 2024-10-02 15:37
It appears during the generating.module.deps part -std options isn't passed to clang

**Comment by ilobilo** [comment] 2024-10-02 20:00
also @waruqi the project uses it's own toolchain, clang and lld

**Comment by waruqi** [comment] 2024-10-04 04:29
it works for me on Fedora.

```console
bash-5.2$ xmake
[ 83%]: compiling.releasedbg kernel/source/arch/x86_64/arch.cpp
[ 84%]: compiling.releasedbg kernel/source/arch/x86_64/system/gdt.cpp
[ 85%]: compiling.releasedbg kernel/source/arch/x86_64/system/idt.cpp
[ 85%]: compiling.releasedbg kernel/source/arch/x86_64/system/lapic.cpp
[ 86%]: compiling.releasedbg kernel/source/lib/log.cpp
[ 87%]: compiling.releasedbg kernel/source/lib/panic.cpp
[ 89%]: compiling.releasedbg kernel/source/libc/stdio.cpp
[ 90%]: compiling.releasedbg kernel/source/libc/stdlib.cpp
[ 91%]: compiling.releasedbg kernel/source/misc/cxxabi.cpp
[ 92%]: compiling.releasedbg kernel/source/misc/ubsan.cpp
[ 93%]: compiling.releasedbg kernel/source/system/cpu.cpp
[ 93%]: compiling.releasedbg kernel/source/system/memory/heap.cpp
[ 94%]: compiling.releasedbg kernel/source/system/memory/pmm.cpp
[ 95%]: compiling.releasedbg kernel/source/system/memory/vmm.cpp
[ 96%]: linking.releasedbg ilobilix.elf
 => copying target files to temporary iso directory...
 => building the iso...
xorriso 1.5.6 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:build/ilobilix/x86_64/releasedbg/image-x86_64.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 40.2g free
Added to ISO image: directory '/'='/tmp/.xmake995/241004/ilobilix.iso.dir'
xorriso : UPDATE :      13 files added in 1 seconds
xorriso : UPDATE :      13 files added in 1 seconds
xorriso : UPDATE :  52.04% done
ISO image produced: 3013 sectors
Written to medium : 3013 sectors at LBA 0
Writing to 'stdio:build/ilobilix/x86_64/releasedbg/image-x86_64.iso' completed successfully.

 => installing limine...
[100%]: build ok, spent 5.51s
warning: std and std.compat modules not found ! disabling them for the build, maybe try to add --sdk=<PATH/TO/LLVM>
$ cat ./kernel/source/arch/x86_64/system/lapic.cpp
// Copyright (C) 2024  ilobilo

module x86_64.system.lapic;
import system.memory.virt; <-------------------- add this line now

import system.memory;
import system.cpu.self;
import system.cpu;
import lib;
import std;

bash-5.2$ xmake
[100%]: build ok, spent 0.913s
warning: std and std.compat modules not found ! disabling them for the build, maybe try to add --sdk=<PATH/TO/LLVM>
bash-5.2$ xmake
[  0%]: <ilobilix.elf> generating.module.deps kernel/source/arch/x86_64/system/lapic.cpp
[ 85%]: compiling.releasedbg kernel/source/arch/x86_64/system/lapic.cpp
[ 96%]: linking.releasedbg ilobilix.elf
 => copying target files to temporary iso directory...
 => building the iso...
xorriso 1.5.6 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:build/ilobilix/x86_64/releasedbg/image-x86_64.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 40.2g free
Added to ISO image: directory '/'='/tmp/.xmake995/241004/ilobilix.iso.dir'
xorriso : UPDATE :      13 files added in 1 seconds
xorriso : UPDATE :      13 files added in 1 seconds
xorriso : UPDATE :  48.32% done
ISO image produced: 3013 sectors
Written to medium : 3013 sectors at LBA 0
Writing to 'stdio:build/ilobilix/x86_64/releasedbg/image-x86_64.iso' completed successfully.

 => installing limine...
[100%]: build ok, spent 3.083s
warning: std and std.compat modules not found ! disabling them for the build, maybe try to add --sdk=<PATH/TO/LLVM>
warning: add -v for getting more warnings ..
````

**Comment by ilobilo** [comment] 2024-10-04 05:33
yes it sometimes works for me too, but only sometimes.
try adding ``import system.memory.phys;`` or ``import magic_enum;``

**Comment by Arthapz** [comment] 2024-10-04 16:31
i updated the branch, try now @ilobilo

**Comment by Arthapz** [comment] 2024-10-04 16:33
should be fixed by https://github.com/xmake-io/xmake/pull/5686

**Comment by Arthapz** [comment] 2024-10-04 16:34
> It appears during the generating.module.deps part -std option isn't passed to clang

yes, we don't have choice, with clang we need to strip the -std= flag because with it, clang try to enable module discovery machinery, unfortunaly, header unit support is not what llvm team focus on, so i'll recommend to not using them, and only use named module

**Comment by ilobilo** [comment] 2024-10-04 16:36
> should be fixed by https://github.com/xmake-io/xmake/pull/5686

Thank you very much, I'll try it out when I have the time

**Closed** 2024-10-04 16:36 UTC
Labels: bug
