### ISSUE TITLE
Implement a way to switch stl library for clang (and maybe gcc)

### ISSUE THREAD

**Issue by Arthapz** [xmake-io/xmake#4477] opened 2023-12-07 11:18 UTC
### Is your feature request related to a problem? Please describe.

Currently to switch stl library for clang we need to hardcode some clang flags for targets and packages, it can cause some problems when a clang package is built with libstdc++ and the project target built with libc++

### Describe the solution you'd like

i personnaly think it's better to add a global flag --cxxstl (which will be no-op on msvc, change stl library on clang and maybe gcc)
and it would be used to discriminate package (so for example we could install fmt library with libstdc++ AND libc++)

### Describe alternatives you've considered

A toolchain or a policy

### Additional context
the discussion of this feature begin here:
https://github.com/xmake-io/xmake/pull/4474

and here a first attempt to implement it with a policy
https://github.com/xmake-io/xmake/pull/4463

**Comment by waruqi** [comment] 2023-12-07 13:19
I think it's possible to configure it using a more generic abstract API like set_cxxstl("libc++"), but it shouldn't go for set_cxxstl("clang::libc++"). This is because stl libraries are not fully compiler-bound, e.g. stl in ndk does not distinguish between gcc/clang.

for example:

### disable stl

```lua
set_cxxstl("none")
```

or

```console
$ xmake f --cxxstl=none
```

it will not add any stl library.

### gcc/clang

```lua
set_cxxstl("libc++")
set_cxxstl("libstdc++")
```

### NDK

```lua
set_cxxstl("c++_static")
set_cxxstl("c++_shared")
set_cxxstl("gnustl_static")
set_cxxstl("gnustl_shared")
set_cxxstl("stlport_shared")
set_cxxstl("stlport_static")   
```

If we want to set it according to the compiler, we can do so:

```lua
target("test")
    on_config(function (target)
        if not target:is_plat("android") and target:has_tool("ld", "clang", "clangxx") then
            target:set("cxxstl", "libc++")  
        end
    end)
```

And we can use `xmake f --cxxstl=libc++` now. And we can also set it for android ndk. `xmake f -p android --cxxstl=c++_static`.  and we can also continune to use `--ndk_cxxstl=`. (In the future it may be marked as deprecated.)

### package

add a bultin config `cxxstl` for package. and we can get it via `package:config("cxxstl")`

And we need pass `--cxxstl` to `package.tools.*` in on_install().

**Comment by Arthapz** [comment] 2023-12-07 13:59
Maybe to have more consistency with android ndk we can use

```lua
# libc++ shared
set_cxxstl("c++")

# libc++ static
set_cxxstl("c++_static")

# libstdc++ shared
set_cxxstl("gnustl")

# libstd++ static
set_cxxstl("gnustl_static")

# android only
set_cxxstl("stlport")
set_cxxstl("stlport_static")
```

for both regular platform / android

(and continue to support c++_shared / gnustl_shared but as deprecated values)

**Comment by Arthapz** [comment] 2023-12-07 14:19
there is an other possibility, reuse set_runtimes to support these values, so we don't need to introduce a new interface ?

**Comment by waruqi** [comment] 2023-12-07 14:57
> > Thinking about it, it's not very different from the Visual Studio runtime, I wonder if those configs could be merged with set_runtimes, or set_runtimes deprecated for set_cxxstl
> 
> yeah and it could be use to switch all kind of runtimes, like libc
> 
> ```lua
> set_runtimes("muslc", "libc++")
> ```

sure, you can try.

**Comment by shaqtsui** [comment] 2023-12-22 13:50
Can mege vs_runtime to this feature?
As I know the vs_runtime is almost about c std library.

**Comment by Arthapz** [comment] 2023-12-22 14:09
> Can mege vs_runtime to this feature?
> 
> As I know the vs_runtime is almost about c std library. 

That's the idea, i'm working on it, but has it is the end of the year, i'm slowly progressent implementing this (and i'm working on a module PR too)

**Comment by waruqi** [comment] 2024-01-24 02:09
I have supported it. https://github.com/xmake-io/xmake/pull/4630

### Supported runtimes
 - msvc: MT, MD, MTd, MDd
 - gcc: stdc++_static, stdc++_shared
 - clang: c++_static, c++_shared, stdc++_static, stdc++_shared
 - ndk: c++_static, c++_shared, stdc++_static, stdc++_shared, stlport_static, stlport_shared, gnustl_static, gnustl_shared

### New options and configs

- `xmake f --runtimes=`
  - `xmake f --runtimes=MTd`
  - `xmake f --runtimes=MT,c++_static`
- `add_configs("runtimes")` in package
- `package:runtimes()`, `package:has_runtime()`, `target:runtimes()`, `target:has_runtime()`
  - For msvc: runtimes() -> MT, MD, MTd, MDd (only one, always return string)
  - For gcc: runtimes() -> stdc++_static, stdc++_shared
  - For clang: runtimes() -> c++_static, c++_shared, stdc++_static, stdc++_shared (maybe return table)
- `add_runtimes()`
  - `add_runtimes("MTd", "c++_static")` 
- `add_requires()`
  - `add_requires("xxx", {configs = {runtimes = "MT,c++_static"}})`
  
### Fully compatible with vs_runtime, but we added some deprecated warning tips

  - `xmake f --vs_runtime/--ndk_cxxstl`
  - `add_configs("vs_runtime")`
  - `package:config("vs_runtime")`

**Comment by waruqi** [comment] 2024-01-26 15:02
I have merged it.

**Closed by waruqi** 2024-01-26 15:02 UTC
Labels: feature request

**Comment by SirLynix** [comment] 2024-01-26 16:29
My CI just broke on the dev branch: https://github.com/NazaraEngine/NazaraEngine/actions/runs/7670670489/job/20907370128

which is a bit weird

**Comment by SirLynix** [comment] 2024-01-26 19:41
> My CI just broke on the dev branch: https://github.com/NazaraEngine/NazaraEngine/actions/runs/7670670489/job/20907370128
> 
> which is a bit weird, it looks like a version issue

It seems to have something with the hash changes, I can reproduce it locally
```
error: package(qt5gui/5.15.2:{"debug=true","runtimes=MD"}): conflict dependences with package(qt5gui/latest:{"debug=true","runtimes=MD"}) in nodeeditor!
```

the weird thing is that it happens only on Windows

**Comment by waruqi** [comment] 2024-01-27 14:42
```
_check_package_depconflicts
  - qt5core nodeeditor.qt5core
  - qt5gui nodeeditor.qt5gui
  - qt5widgets nodeeditor.qt5widgets
  - qt5gui nodeeditor.qt5widgets.qt5gui
error: package(qt5gui/5.15.2:{"debug=true","runtimes=MD"}): conflict dependences with package(qt5gui/latest:{"debug=true","runtimes=MD"}) in nodeeditor!
```

nodeeditor.qt5gui -> latest
nodeeditor.qt5widgets.qt5gui -> 5.15.2

https://github.com/xmake-io/xmake-repo/blob/6a92031e492b182be8cf4ab04f87ab257f2d68ef/packages/q/qt5widgets/xmake.lua#L6

```
version = package:version_str()
```

package:version_str() has been resolved as 5.15.2

**Comment by SirLynix** [comment] 2024-01-27 14:49
Yes but why does it happen only now? and why only on Windows? And why does qt5gui takes "latest" version?

**Comment by waruqi** [comment] 2024-01-27 15:23
https://github.com/xmake-io/xmake/blob/97ebae3c85e8bb7cfef13b02415e4a5798b13234/xmake/modules/private/action/require/impl/package.lua#L833

here, it will affect package cache key. https://github.com/xmake-io/xmake/blob/97ebae3c85e8bb7cfef13b02415e4a5798b13234/xmake/modules/private/action/require/impl/package.lua#L930

**Comment by waruqi** [comment] 2024-01-27 15:49
try it again.

**Comment by Arthapz** [comment] 2024-01-27 16:29
packages seems broken

```
> xrepo install -vD --configs='runtimes="c++_shared"' libjpeg-turbo  
error: ...positories\xmake-repo\packages\l\libjpeg-turbo\xmake.lua:51: attempt to index a nil value
stack traceback:
    [...positories\xmake-repo\packages\l\libjpeg-turbo\xmake.lua:51]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:369]:

  => install libjpeg-turbo 3.0.1 .. ❌
❗ error: @programdir\core\main.lua:306: @programdir\modules\async\runjobs.lua:320: ...\modules\private\action\require\impl\actions\install.lua:474: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:957]:
    [...\modules\private\action\require\impl\actions\install.lua:474]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:333]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:237]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:957: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:306: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
⚠ warning: please use package:runtimes() or package:has_runtime() instead of package:config("vs_runtime")
❗ error: @programdir\core\main.lua:306: @programdir\core\sandbox\modules\os.lua:378: execv(C:\Users\arthu\xmake\xmake.exe require -v -D -j 26 --extra={system=false,configs={runtimes=\"c++_shared\"}} libjpeg-turbo)
 failed(-1)
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:957]:
    [@programdir\core\sandbox\modules\os.lua:378]:
    [@programdir\modules\private\xrepo\action\install.lua:300]: in function '_install_packages'
    [@programdir\modules\private\xrepo\action\install.lua:307]:
    [@programdir\modules\private\xrepo\main.lua:196]:
    [@programdir\plugins\lua\main.lua:124]:
    [C]: in function 'xpcall'
    [@programdir\core\base\utils.lua:280]:
    [@programdir\core\base\task.lua:501]: in function 'run'
    [@programdir\core\main.lua:304]: in function 'cotask'
    [@programdir\core\base\scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:957: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:306: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
 ```
 
 https://github.com/xmake-io/xmake-repo/blob/6a92031e492b182be8cf4ab04f87ab257f2d68ef/packages/l/libjpeg-turbo/xmake.lua#L51

**Comment by SirLynix** [comment] 2024-01-27 17:12
> try it again.

It's working now, thanks!

**Comment by waruqi** [comment] 2024-01-28 10:27
> some packages seems broken
> 
> ```
> > xrepo install -vD --configs='runtimes="c++_shared"' libjpeg-turbo  
> error: ...positories\xmake-repo\packages\l\libjpeg-turbo\xmake.lua:51: attempt to index a nil value
> stack traceback:
>     [...positories\xmake-repo\packages\l\libjpeg-turbo\xmake.lua:51]: in function 'script'
>     [...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
>     [...\modules\private\action\require\impl\actions\install.lua:369]:
> 
>   => install libjpeg-turbo 3.0.1 .. ❌
> ❗ error: @programdir\core\main.lua:306: @programdir\modules\async\runjobs.lua:320: ...\modules\private\action\require\impl\actions\install.lua:474: install failed!
> stack traceback:
>     [C]: in function 'error'
>     [@programdir\core\base\os.lua:957]:
>     [...\modules\private\action\require\impl\actions\install.lua:474]: in function 'catch'
>     [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
>     [...\modules\private\action\require\impl\actions\install.lua:333]:
>     [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
>     [@programdir\modules\async\runjobs.lua:237]:
> 
> stack traceback:
>         [C]: in function 'error'
>         @programdir\core\base\os.lua:957: in function 'base/os.raiselevel'
>         (...tail calls...)
>         @programdir\core\main.lua:306: in upvalue 'cotask'
>         @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
> ⚠ warning: please use package:runtimes() or package:has_runtime() instead of package:config("vs_runtime")
> ❗ error: @programdir\core\main.lua:306: @programdir\core\sandbox\modules\os.lua:378: execv(C:\Users\arthu\xmake\xmake.exe require -v -D -j 26 --extra={system=false,configs={runtimes=\"c++_shared\"}} libjpeg-turbo)
>  failed(-1)
> stack traceback:
>     [C]: in function 'error'
>     [@programdir\core\base\os.lua:957]:
>     [@programdir\core\sandbox\modules\os.lua:378]:
>     [@programdir\modules\private\xrepo\action\install.lua:300]: in function '_install_packages'
>     [@programdir\modules\private\xrepo\action\install.lua:307]:
>     [@programdir\modules\private\xrepo\main.lua:196]:
>     [@programdir\plugins\lua\main.lua:124]:
>     [C]: in function 'xpcall'
>     [@programdir\core\base\utils.lua:280]:
>     [@programdir\core\base\task.lua:501]: in function 'run'
>     [@programdir\core\main.lua:304]: in function 'cotask'
>     [@programdir\core\base\scheduler.lua:404]:
> 
> stack traceback:
>         [C]: in function 'error'
>         @programdir\core\base\os.lua:957: in function 'base/os.raiselevel'
>         (...tail calls...)
>         @programdir\core\main.lua:306: in upvalue 'cotask'
>         @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
> ```
> 
> https://github.com/xmake-io/xmake-repo/blob/6a92031e492b182be8cf4ab04f87ab257f2d68ef/packages/l/libjpeg-turbo/xmake.lua#L51

try it again .https://github.com/xmake-io/xmake/commit/4d8b4ad55eb3ccee0dd0e9c0fc0bafbb55ca04e6

**Comment by SirLynix** [comment] 2024-01-28 10:29
By the way, wouldn't this change be a great time to change the default runtime from MT to MD on Windows?

MD is the default runtime set by Visual Studio and is the less prone to having issues with DLL

**Comment by waruqi** [comment] 2024-01-28 10:42
> By the way, wouldn't this change be a great time to change the default runtime from MT to MD on Windows?
> 
> MD is the default runtime set by Visual Studio and is the less prone to having issues with DLL

But it will break more things, especially buildhash

**Comment by waruqi** [comment] 2024-01-28 10:48
If we don't set any vs runtime flags, cl.exe uses MT by default, and if we switch to MD. xmake must set MD built-in by default, even if the user doesn't configure any flags for the target. this is going to break a lot of current projects, not just packages.

Also, if the user sets vs runtimes, xmake will need to determine which of the built-in MT runtimes to remove, which also adds complexity to the implementation and leads to more problems.

**Comment by Arthapz** [comment] 2024-01-28 14:21
> > some packages seems broken
> > ```
> > > xrepo install -vD --configs='runtimes="c++_shared"' libjpeg-turbo  
> > error: ...positories\xmake-repo\packages\l\libjpeg-turbo\xmake.lua:51: attempt to index a nil value
> > stack traceback:
> >     [...positories\xmake-repo\packages\l\libjpeg-turbo\xmake.lua:51]: in function 'script'
> >     [...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
> >     [...\modules\private\action\require\impl\actions\install.lua:369]:
> > 
> >   => install libjpeg-turbo 3.0.1 .. ❌
> > ❗ error: @programdir\core\main.lua:306: @programdir\modules\async\runjobs.lua:320: ...\modules\private\action\require\impl\actions\install.lua:474: install failed!
> > stack traceback:
> >     [C]: in function 'error'
> >     [@programdir\core\base\os.lua:957]:
> >     [...\modules\private\action\require\impl\actions\install.lua:474]: in function 'catch'
> >     [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
> >     [...\modules\private\action\require\impl\actions\install.lua:333]:
> >     [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
> >     [@programdir\modules\async\runjobs.lua:237]:
> > 
> > stack traceback:
> >         [C]: in function 'error'
> >         @programdir\core\base\os.lua:957: in function 'base/os.raiselevel'
> >         (...tail calls...)
> >         @programdir\core\main.lua:306: in upvalue 'cotask'
> >         @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
> > ⚠ warning: please use package:runtimes() or package:has_runtime() instead of package:config("vs_runtime")
> > ❗ error: @programdir\core\main.lua:306: @programdir\core\sandbox\modules\os.lua:378: execv(C:\Users\arthu\xmake\xmake.exe require -v -D -j 26 --extra={system=false,configs={runtimes=\"c++_shared\"}} libjpeg-turbo)
> >  failed(-1)
> > stack traceback:
> >     [C]: in function 'error'
> >     [@programdir\core\base\os.lua:957]:
> >     [@programdir\core\sandbox\modules\os.lua:378]:
> >     [@programdir\modules\private\xrepo\action\install.lua:300]: in function '_install_packages'
> >     [@programdir\modules\private\xrepo\action\install.lua:307]:
> >     [@programdir\modules\private\xrepo\main.lua:196]:
> >     [@programdir\plugins\lua\main.lua:124]:
> >     [C]: in function 'xpcall'
> >     [@programdir\core\base\utils.lua:280]:
> >     [@programdir\core\base\task.lua:501]: in function 'run'
> >     [@programdir\core\main.lua:304]: in function 'cotask'
> >     [@programdir\core\base\scheduler.lua:404]:
> > 
> > stack traceback:
> >         [C]: in function 'error'
> >         @programdir\core\base\os.lua:957: in function 'base/os.raiselevel'
> >         (...tail calls...)
> >         @programdir\core\main.lua:306: in upvalue 'cotask'
> >         @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://github.com/xmake-io/xmake-repo/blob/6a92031e492b182be8cf4ab04f87ab257f2d68ef/packages/l/libjpeg-turbo/xmake.lua#L51
> 
> try it again .[4d8b4ad](https://github.com/xmake-io/xmake/commit/4d8b4ad55eb3ccee0dd0e9c0fc0bafbb55ca04e6)


the error changed, but still failing

```
>xrepo install --yes -vD --toolchain=clang --configs='runtimes="c++_shared"' libjpeg-turbo  
error: @programdir\modules\package\tools\cmake.lua:369: attempt to concatenate a table value (local 'runtimes')
stack traceback:
    [@programdir\modules\package\tools\cmake.lua:369]: in function '_get_configs_for_windows'
    [@programdir\modules\package\tools\cmake.lua:709]: in function '_get_configs'
    [@programdir\modules\package\tools\cmake.lua:1015]: in function 'install'
    [...positories\xmake-repo\packages\l\libjpeg-turbo\xmake.lua:61]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:369]:

  => install libjpeg-turbo 3.0.1 .. ❌
❗ error: @programdir\core\main.lua:306: @programdir\modules\async\runjobs.lua:320: ...\modules\private\action\require\impl\actions\install.lua:474: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:957]:
    [...\modules\private\action\require\impl\actions\install.lua:474]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:333]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:237]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:957: in function 'base/os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:306: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
⚠ warning: please use package:runtimes() or package:has_runtime() instead of package:config("vs_runtime")
❗ error: .\xmake\core\main.lua:306: .\xmake\core\sandbox\modules\os.lua:378: execv(C:\Users\arthu\xmake\xmake.exe require -y -v -D -j 26 --extra={system=false,configs={runtimes=\"c++_shared\"}} libjpeg-turbo) fail
ed(-1)
stack traceback:
    [C]: in function 'error'
    [.\xmake\core\base\os.lua:957]:
    [.\xmake\core\sandbox\modules\os.lua:378]:
    [.\xmake\modules\private\xrepo\action\install.lua:300]: in function '_install_packages'
    [.\xmake\modules\private\xrepo\action\install.lua:307]:
    [.\xmake\modules\private\xrepo\main.lua:196]:
    [.\xmake\plugins\lua\main.lua:124]:
    [C]: in function 'xpcall'
    [.\xmake\core\base\utils.lua:280]:
    [.\xmake\core\base\task.lua:501]: in function 'run'
    [.\xmake\core\main.lua:304]: in function 'cotask'
    [.\xmake\core\base\scheduler.lua:404]:

stack traceback:
        [C]: in function 'error'
        .\xmake\core\base\os.lua:957: in function 'os.raiselevel'
        (...tail calls...)
        .\xmake\core\main.lua:306: in upvalue 'cotask'
        .\xmake\core\base\scheduler.lua:404: in function <.\xmake\core\base\scheduler.lua:397>
```

**Comment by waruqi** [comment] 2024-01-28 14:51
try it again.

**Comment by Arthapz** [comment] 2024-01-28 15:31
> try it again.

```
error: ...positories\xmake-repo\packages\l\libjpeg-turbo\xmake.lua:51: attempt to index a nil value
stack traceback:
    [...positories\xmake-repo\packages\l\libjpeg-turbo\xmake.lua:51]: in function 'script'
    [...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
    [...\modules\private\action\require\impl\actions\install.lua:369]:

  => install libjpeg-turbo 3.0.1 .. ❌
❗ error: @programdir\core\main.lua:306: @programdir\modules\async\runjobs.lua:320: ...\modules\private\action\require\impl\actions\install.lua:474: install failed!
stack traceback:
    [C]: in function 'error'
    [@programdir\core\base\os.lua:957]:
    [...\modules\private\action\require\impl\actions\install.lua:474]: in function 'catch'
    [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
    [...\modules\private\action\require\impl\actions\install.lua:333]:
    [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
    [@programdir\modules\async\runjobs.lua:237]:

stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:957: in function 'os.raiselevel'
        (...tail calls...)
        @programdir\core\main.lua:306: in upvalue 'cotask'
        @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
```

**Comment by waruqi** [comment] 2024-01-29 01:23
> > try it again.
> 
> ```
> error: ...positories\xmake-repo\packages\l\libjpeg-turbo\xmake.lua:51: attempt to index a nil value
> stack traceback:
>     [...positories\xmake-repo\packages\l\libjpeg-turbo\xmake.lua:51]: in function 'script'
>     [...dir\modules\private\action\require\impl\utils\filter.lua:114]: in function 'call'
>     [...\modules\private\action\require\impl\actions\install.lua:369]:
> 
>   => install libjpeg-turbo 3.0.1 .. ❌
> ❗ error: @programdir\core\main.lua:306: @programdir\modules\async\runjobs.lua:320: ...\modules\private\action\require\impl\actions\install.lua:474: install failed!
> stack traceback:
>     [C]: in function 'error'
>     [@programdir\core\base\os.lua:957]:
>     [...\modules\private\action\require\impl\actions\install.lua:474]: in function 'catch'
>     [@programdir\core\sandbox\modules\try.lua:123]: in function 'try'
>     [...\modules\private\action\require\impl\actions\install.lua:333]:
>     [...modules\private\action\require\impl\install_packages.lua:479]: in function 'jobfunc'
>     [@programdir\modules\async\runjobs.lua:237]:
> 
> stack traceback:
>         [C]: in function 'error'
>         @programdir\core\base\os.lua:957: in function 'os.raiselevel'
>         (...tail calls...)
>         @programdir\core\main.lua:306: in upvalue 'cotask'
>         @programdir\core\base\scheduler.lua:404: in function <@programdir\core\base\scheduler.lua:397>
> ```

it works for me. https://github.com/xmake-io/xmake-repo/actions/runs/7689614933

and on my win machine.

**Comment by Arthapz** [comment] 2024-01-29 02:22
> machine.

Try with --toolchain=clang --runtimes=c++_shared

**Comment by waruqi** [comment] 2024-01-29 03:05
> > machine.
> 
> Try with --toolchain=clang --runtimes=c++_shared on Windows

Windows packages are always strongly bound to msvc, and xmake has never supported switching to another toolchain.

I have fixed this error, but even though I fixed this bug, the actual msvc is still used.

**Comment by Arthapz** [comment] 2024-01-29 11:49
> > > machine.
> > 
> > 
> > Try with --toolchain=clang --runtimes=c++_shared on Windows
> 
> Windows packages are always strongly bound to msvc, and xmake has never supported switching to another toolchain.
> 
> I have fixed this error, but even though I fixed this bug, the actual msvc is still used.

i always assumed it was working :D, the only issue i had was that clang compiled package were installing along side msvc one
but is fixed with this features request

> even though I fixed this bug, the actual msvc is still used.

i think it's because the generator used is msbuild, on some other libraries i have clang that is used so it depend of the package
